"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-24y1t3z276@s87(56xos0_8uzubrm7-_ybo^c^w1*ql5s$b4m@"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'main'
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "ru"

TIME_ZONE = "Asia/Bishkek"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATIC_URL = "/static/"

# Extra places for collectstatic to find static files.
# STATICFILES_DIRS = (os.path.join(BASE_DIR, "static"),)

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Public URL this site is reachable at — used to build the RedirectUrl /
# webhookUrl Finik calls back to, so it must be a real publicly-reachable
# HTTPS origin in production (Finik's servers need to reach the webhook).
SITE_URL = config("SITE_URL", default="http://127.0.0.1:8000").rstrip("/")

# Price of one Winx x Ques Secret Box, сом. The 5% puzzle discount (see
# winx_submit_order) is applied on top of quantity * this price.
WINX_BOX_PRICE_KGS = config("WINX_BOX_PRICE_KGS", default=990, cast=int)

# --- Finik ---
# https://www.finik.kg/documentation/web-sdk/ — payment gateway for the
# Winx Secret Box checkout. While FINIK_TEST_MODE=True (or credentials
# aren't set), buyers are sent to a local fake payment page instead, so
# the whole order -> pay -> Telegram-notify flow is testable without a
# live Finik account.
FINIK_TEST_MODE = config("FINIK_TEST_MODE", default=True, cast=bool)
# "beta" for testing against Finik's sandbox (no real money moves),
# "prod" once ready to accept real payments.
FINIK_MODE = config("FINIK_MODE", default="beta")
FINIK_API_KEY = config("FINIK_API_KEY", default="")
# Stored in .env with real newlines replaced by literal "\n" — swapped
# back to real newlines here. See main/finik.py for the signing algorithm.
FINIK_PRIVATE_KEY = config("FINIK_PRIVATE_KEY", default="").replace("\\n", "\n")
FINIK_ACCOUNT_ID = config("FINIK_ACCOUNT_ID", default="")
FINIK_QR_NAME = config("FINIK_QR_NAME", default="QUES x WINX Secret Box")
