# Generated by Django 4.2.17 on 2026-09-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WinxOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255, verbose_name="ФИО")),
                ("phone", models.CharField(max_length=32, verbose_name="Телефон")),
                (
                    "method",
                    models.CharField(
                        choices=[("delivery", "Доставка"), ("pickup", "Самовывоз")],
                        max_length=16,
                        verbose_name="Способ получения",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Адрес доставки"
                    ),
                ),
                (
                    "discount_claimed",
                    models.BooleanField(default=False, verbose_name="Скидка 5% (пазл)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата заказа"),
                ),
            ],
            options={
                "verbose_name": "Заказ Winx Secret Box",
                "verbose_name_plural": "Заказы Winx Secret Box",
                "ordering": ["-created_at"],
            },
        ),
    ]
