# Generated by Django 4.2.17 on 2026-09-07 12:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="winxorder",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Сумма, сом"
            ),
        ),
        migrations.AddField(
            model_name="winxorder",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Оплачен"),
        ),
        migrations.AddField(
            model_name="winxorder",
            name="payment_id",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="ID платежа Finik"
            ),
        ),
        migrations.AddField(
            model_name="winxorder",
            name="qr_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="winxorder",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Количество боксов"
            ),
        ),
        migrations.AddField(
            model_name="winxorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает оплаты"),
                    ("paid", "Оплачен"),
                    ("failed", "Не оплачен / отменён"),
                ],
                default="pending",
                max_length=16,
                verbose_name="Статус оплаты",
            ),
        ),
    ]
